name: Deploy to S3

on:
  workflow_dispatch:
    inputs:
      aws-region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'us-east-1'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws-region }}

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://static-website-nida --delete
